version: "2"
services:

  apache:
    build:
      context: ./config/apache-php
      dockerfile: Dockerfile
    container_name: "ci_apache"
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "./public:/var/www/html:rw"
      - "./config/apache-php/php.ini:/etc/php.d/php.ini"

  mysql:
    image: mysql:5.6
    container_name: "ci_mysql"
    restart: always
    command: "--max_allowed_packet=4096M --default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"
